default_stages: [pre-commit]
default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, jupyter ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: ^(docs|tests)\/
        language_version: python3.9
        pass_filenames: false
        args: [
          --namespace-packages,
          --explicit-package-bases,
          --ignore-missing-imports,
          --non-interactive,
          --install-types
        ]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.27
    hooks:
      # Compile requirements
      - id: pip-compile
        name: pip-compile requirements
        args: [pyproject.toml, -o, requirements.txt, --upgrade]
        files: ^pyproject\.toml$
      - id: pip-compile
        name: pip-compile dev requirements
        args: [pyproject.toml, -o, dev-requirements.txt, --extra, dev, --upgrade]
        files: ^pyproject\.toml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, test, refactor, perf, docs, style, build, ci, revert, chore, upgrade, review]
