# This workflow runs edgetest on lazyscribe @ 17:20 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@v1.5
        with:
          edgetest-flags: '-c pyproject.toml -r requirements.txt --export'
          base-branch: 'develop'
          skip-pr: 'false'
