# This workflow runs edgetest on lazyscribe @ 17:35 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
  workflow_dispatch:
jobs:
  edgetest:
    runs-on: ubuntu-24.04
    name: running edgetest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@v1.6
        with:
          edgetest-flags: '-c pyproject.toml -r requirements.txt --export'
          base-branch: 'main'
          skip-pr: 'true'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.10'
      - name: Compile dev-requirements.txt
        run: uv pip compile pyproject.toml -o dev-requirements.txt --extra dev --upgrade
      - name: Update uv lock
        run: uv lock
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: edgetest-patch
          base: main
          delete-branch: true
          title: 'upgrade(deps): update dependency version bounds'
          commit-message: 'upgrade(deps): update dependency version bounds'
          body: Automated changes by [run-edgetest-action](https://github.com/edgetest-dev/run-edgetest-action) GitHub action
          add-paths: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt
            uv.lock
