# Install and test

name: Test package

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version:
                    - '3.10'
                    - '3.11'
                    - '3.12'
                    - '3.13'
                    - '3.14'
        steps:
            - uses: actions/checkout@v6

            - name: Install uv and set the Python version
              uses: astral-sh/setup-uv@v7
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --locked --all-extras --dev

            - name: Run ruff QA checks
              run: uv run ruff check .

            - name: Check formatting
              run: uv run ruff format . --check

            - name: Check static typing
              run: uv run mypy lazyscribe

            - name: Run unit testing
              run: uv run pytest tests --cov=./ --cov-report=xml

            - name: Coverage comment
              id: coverage_comment
              uses: py-cov-action/python-coverage-comment-action@v3
              if: matrix.python-version == '3.14'
              with:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Store Pull Request comment to be posted
              uses: actions/upload-artifact@v7
              if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true' && matrix.python-version == '3.14'
              with:
                # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
                name: python-coverage-comment-action
                # If you use a different name, update COMMENT_FILENAME accordingly
                path: python-coverage-comment-action.txt
